---
- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  ignore_errors: yes

- name: Disable swap in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '(^.*\sswap\s.*$)'
    replace: '# \1'
  ignore_errors: yes

- name: Ensure required kernel modules are loaded at boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: "0644"

- name: Configure sysctl for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    mode: "0644"

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
