---
- name: Add Docker repo (for containerd)
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/docker.repo
    content: |
      [docker]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/9/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg
    mode: "0644"

- name: Refresh dnf cache
  ansible.builtin.command: dnf clean all && dnf makecache
  args:
    warn: false

- name: Install containerd package
  ansible.builtin.dnf:
    name: "{{ containerd_pkg_name }}"
    state: present

- name: Create default containerd config if missing
  ansible.builtin.command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Ensure systemd cgroup is enabled in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  ignore_errors: yes

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
