---
- name: Add Docker (containerd) repo
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/docker.repo
    content: |
      [docker]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/9/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg
  become: yes

- name: Refresh DNF cache
  ansible.builtin.command: dnf clean all && dnf makecache
  args:
    warn: false
  become: yes

- name: Install containerd
  ansible.builtin.dnf:
    name:
      - containerd.io
    state: present
  become: yes

- name: Configure containerd
  ansible.builtin.command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  become: yes

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
  become: yes
