---
- name: Add Docker repo for containerd
  yum_repository:
    name: docker
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install containerd
  yum:
    name: containerd.io
    state: present


- name: Configure containerd
  block:
    - command: containerd config default | tee /etc/containerd/config.toml
    - replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: true
    state: started
