---
# 1. PRE-FLIGHT: Ensure Python + Update System (without Kubernetes repo)
- name: Pre-flight setup
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure python3 is installed for Ansible
      ansible.builtin.dnf:
        name: python3
        state: present
        disablerepo: kubernetes

    - name: Update system packages safely (without Kubernetes repo)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        disablerepo: kubernetes

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot triggered by Ansible after updates"
        connect_timeout: 30
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 10
      when: ansible_facts.reboot_required is defined

# 2. BASE SYSTEM PREP: swap, sysctl, modules
- name: Base system configuration
  hosts: all
  become: yes
  roles:
    - base

# 3. INSTALL CONTAINERD & KUBERNETES
- name: Install container runtime & Kubernetes components
  hosts: all
  become: yes
  roles:
    - containerd
    - kubernetes

# 4. INITIALIZE CONTROL PLANE
- name: Initialize Kubernetes control plane
  hosts: masters
  become: yes
  roles:
    - master-init

# 5. JOIN WORKERS
- name: Join worker nodes to cluster
  hosts: workers
  become: yes
  roles:
    - worker-join

# 6. INSTALL CNI
- name: Deploy CNI network plugin
  hosts: masters
  become: yes
  roles:
    - cni
