---
- name: Pre-flight - ensure python3 and update OS (kubernetes repo disabled)
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure python3 is installed for Ansible
      ansible.builtin.dnf:
        name: python3
        state: present
        disablerepo: kubernetes

    - name: Update system packages (without kubernetes repo)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        disablerepo: kubernetes

    - name: Reboot if kernel update requires (safe)
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
        connect_timeout: 30
        reboot_timeout: 300
      when: ansible_facts.get('reboot_required', False)

- name: Base system configuration (swap, sysctl, modules)
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - base

- name: Install containerd and Kubernetes packages
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - containerd
    - kubernetes

- name: Initialize Kubernetes control plane on masters
  hosts: masters
  become: yes
  gather_facts: yes
  roles:
    - master-init

- name: Join worker nodes to the cluster
  hosts: workers
  become: yes
  gather_facts: yes
  roles:
    - worker-join

- name: Deploy CNI plugin on master(s)
  hosts: masters
  become: yes
  gather_facts: yes
  roles:
    - cni
