---
- name: Initialize control plane if not already present
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} --kubernetes-version=v{{ kubernetes_version }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  failed_when: kubeadm_init.rc != 0 and ('already initialized' not in (kubeadm_init.stderr | default('')))

- name: Ensure kubeconfig for root
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    creates: $HOME/.kube/config

- name: Try to extract join command from kubeadm init output
  ansible.builtin.set_fact:
    raw_join_lines: "{{ kubeadm_init.stdout_lines | select('search','kubeadm join') | list }}"
  when: kubeadm_init is defined

- name: Create join command via token if none found
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: printed_join
  when: raw_join_lines is not defined or raw_join_lines | length == 0

- name: Set join_cmd fact
  ansible.builtin.set_fact:
    join_cmd: >-
      {{ ( (raw_join_lines|first) | default('') ) | default(printed_join.stdout) }}

- name: Write join script to /tmp/kube_join_cmd.sh
  ansible.builtin.copy:
    dest: /tmp/kube_join_cmd.sh
    content: |
      #!/bin/bash
      set -e
      {{ join_cmd }} --ignore-preflight-errors=all
    mode: "0755"
