---
- name: Wait for kubeconfig to exist
  ansible.builtin.wait_for:
    path: /root/.kube/config
    state: present
    timeout: 120

- name: Apply Flannel CNI manifest
  ansible.builtin.shell: kubectl apply -f {{ flannel_manifest }}
  args:
    warn: false
  register: flannel_apply
  failed_when: flannel_apply.rc != 0 and ('already exists' not in flannel_apply.stdout)
