---
- name: Apply Flannel CNI
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    warn: false
  when: inventory_hostname in groups['masters']
